import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Legacy aliases (kept so v1 UI still compiles)
        ink: { DEFAULT: '#0b0d12', soft: '#1a1d26' },
        paper: { DEFAULT: '#f7f7f5', raised: '#ffffff' },
        accent: { DEFAULT: '#4f46e5', soft: '#eef2ff' },

        // Semantic (Phase 2)
        canvas:  'var(--bg-canvas)',
        surface: 'var(--bg-surface)',
        raised:  'var(--bg-raised)',
        sunken:  'var(--bg-sunken)',

        fg: {
          DEFAULT:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted:     'var(--text-muted)',
          inverse:   'var(--text-inverse)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          subtle:  'var(--border-subtle)',
          strong:  'var(--border-strong)',
        },
        brand: {
          50:  'var(--color-brand-50)',
          100: 'var(--color-brand-100)',
          200: 'var(--color-brand-200)',
          300: 'var(--color-brand-300)',
          400: 'var(--color-brand-400)',
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
          700: 'var(--color-brand-700)',
          800: 'var(--color-brand-800)',
          900: 'var(--color-brand-900)',
          DEFAULT: 'var(--bg-accent)',
        },
        neutral: {
          50:  'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        success: {
          50:  'var(--color-success-50)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
        },
        warning: {
          50:  'var(--color-warning-50)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
        },
        danger: {
          50:  'var(--color-danger-50)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
        },
      },
      spacing: {
        0:  'var(--space-0)',
        1:  'var(--space-1)',
        2:  'var(--space-2)',
        3:  'var(--space-3)',
        4:  'var(--space-4)',
        5:  'var(--space-5)',
        6:  'var(--space-6)',
        7:  'var(--space-7)',
        8:  'var(--space-8)',
        9:  'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
      },
      borderRadius: {
        xs:  'var(--radius-xs)',
        sm:  'var(--radius-sm)',
        md:  'var(--radius-md)',
        lg:  'var(--radius-lg)',
        xl:  'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      fontSize: {
        xs:   ['var(--fs-xs)',   { lineHeight: 'var(--lh-snug)' }],
        sm:   ['var(--fs-sm)',   { lineHeight: 'var(--lh-normal)' }],
        base: ['var(--fs-base)', { lineHeight: 'var(--lh-normal)' }],
        md:   ['var(--fs-md)',   { lineHeight: 'var(--lh-normal)' }],
        lg:   ['var(--fs-lg)',   { lineHeight: 'var(--lh-snug)' }],
        xl:   ['var(--fs-xl)',   { lineHeight: 'var(--lh-snug)' }],
        '2xl':['var(--fs-2xl)',  { lineHeight: 'var(--lh-tight)' }],
        '3xl':['var(--fs-3xl)',  { lineHeight: 'var(--lh-tight)' }],
        '4xl':['var(--fs-4xl)',  { lineHeight: 'var(--lh-tight)' }],
        '5xl':['var(--fs-5xl)',  { lineHeight: 'var(--lh-tight)' }],
      },
      fontFamily: {
        sans: ['ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      transitionDuration: {
        75:  'var(--duration-75)',
        150: 'var(--duration-150)',
        250: 'var(--duration-250)',
        400: 'var(--duration-400)',
      },
      transitionTimingFunction: {
        out:  'var(--ease-out)',
        in:   'var(--ease-in)',
        'in-out': 'var(--ease-in-out)',
        spring: 'var(--ease-spring)',
      },
    },
  },
  plugins: [],
} satisfies Config;
