import { prisma } from '@/server/db/client';
import DOMPurify from 'isomorphic-dompurify';
import { themeToCssVars } from '@/server/ai/themeGen';
import { toThemeDTO } from '@/server/db/mappers';
import type { ThemeDTO } from '@/types/models';

export interface BundleFile {
  path: string;
  content: string;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function sanitize(html: string): string {
  return DOMPurify.sanitize(html, {
    // Allow the structural tags Sitecraft pages emit.
    USE_PROFILES: { html: true, svg: true },
    FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'link'],
    FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur'],
    ADD_ATTR: ['data-role', 'data-variant'],
  });
}

function renderNav(
  pages: { slug: string; name: string; navVisible: boolean; orderIdx: number }[],
): string {
  const visible = pages
    .filter((p) => p.navVisible)
    .sort((a, b) => a.orderIdx - b.orderIdx);
  if (visible.length === 0) return '';
  const links = visible
    .map((p) => {
      const href = p.slug === 'home' ? '/index.html' : `/${p.slug}.html`;
      return `<a href="${href}">${escapeHtml(p.name)}</a>`;
    })
    .join('');
  return `<nav class="sc-nav">${links}</nav>`;
}

function renderPage(args: {
  siteName: string;
  pageName: string;
  pageHtml: string;
  pageCss: string;
  themeCss: string;
  library: ThemeDTO['library'];
  nav: string;
}): string {
  const headerHtml = sanitize(args.library.Header.html || '');
  const footerHtml = sanitize(args.library.Footer.html || '');
  const mainHtml = sanitize(args.pageHtml || '');
  const libCss = [
    args.library.Header.css,
    args.library.Footer.css,
    args.library.Button.css,
    args.library.Card.css,
  ]
    .filter(Boolean)
    .join('\n');

  const title = `${escapeHtml(args.pageName)} — ${escapeHtml(args.siteName)}`;
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<style>
*, *::before, *::after { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: var(--color-surface); color: var(--color-ink); font-family: var(--font-body), system-ui, sans-serif; }
${args.themeCss}
${libCss}
${args.pageCss}
</style>
</head>
<body>
${headerHtml}
${args.nav}
<main>
${mainHtml}
</main>
${footerHtml}
</body>
</html>
`;
}

export async function bundleSite(siteId: string): Promise<BundleFile[]> {
  const site = await prisma.site.findUniqueOrThrow({
    where: { id: siteId },
    include: {
      pages: { orderBy: { orderIdx: 'asc' } },
      theme: true,
    },
  });

  if (!site.theme) {
    throw new Error('Site has no theme; generate theme before deploying');
  }
  const theme = toThemeDTO(site.theme);
  const themeCss = themeToCssVars({
    palette: theme.palette,
    tokens: theme.tokens,
    primaryFont: theme.primaryFont,
    secondaryFont: theme.secondaryFont,
  });
  const nav = renderNav(
    site.pages.map((p) => ({
      slug: p.slug,
      name: p.name,
      navVisible: p.navVisible,
      orderIdx: p.orderIdx,
    })),
  );

  const files: BundleFile[] = [];
  for (const page of site.pages) {
    const html = renderPage({
      siteName: site.name,
      pageName: page.name,
      pageHtml: page.pageHtml,
      pageCss: page.pageCss,
      themeCss,
      library: theme.library,
      nav,
    });
    const path = page.slug === 'home' ? 'index.html' : `${page.slug}.html`;
    files.push({ path, content: html });
  }

  if (!files.some((f) => f.path === 'index.html')) {
    const first = site.pages[0];
    if (first) {
      const copy = files.find((f) => f.path === `${first.slug}.html`);
      if (copy) files.push({ path: 'index.html', content: copy.content });
    } else {
      files.push({
        path: 'index.html',
        content: `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(site.name)}</title></head><body><h1>${escapeHtml(site.name)}</h1><p>No pages yet.</p></body></html>`,
      });
    }
  }

  files.push({
    path: 'README.md',
    content: `# ${site.name}\n\nGenerated by Sitecraft on ${new Date().toISOString()}.\n`,
  });

  return files;
}
